### ISSUE TITLE
Thread safe

### ISSUE THREAD

**Issue by kozyr** [Azure-Samples/documentdb-java-todo-app#1]
Is there a reason for using non-thread safe singleton initialization?

**Comment by aliuy** [comment]
Would you kindly provide more details?

The only singleton I'm aware of is the DocumentDB client, which is thread-safe.

**Comment by kozyr** [comment]
```
    public static TodoItemController getInstance() {
        if (todoItemController == null) {
            todoItemController = new TodoItemController(TodoDaoFactory.getDao());
        }
        return todoItemController;
    }
```
You might end up with 100 TodoItemController objects if you get a 100 simultaneous connections at a time.

**Comment by kozyr** [comment]
Similarly, the code might attempt to create 100 databases, and 100 TodoCollections at the same time...

**Comment by yateam** [comment]
Yes, the code seems to be non thread safe. Could you give some explanation how to work with this example in concurrent systems

**Comment by aliuy** [comment]
Apologies on the miss - I've just updated the sample to create the singleton at class-load time:  https://github.com/Azure-Samples/documentdb-java-todo-app/commit/ce071d454a6cc3455249e32bbb40cda8c76418f5
